[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:http]
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
command=/app/.venv/bin/gunicorn --worker-tmp-dir /dev/shm -w 4 -b %(ENV_HTTP_HOST)s:%(ENV_HTTP_PORT)s --access-logfile - --proxy-protocol auto --forwarded-allow-ips=%(ENV_TRUST_PROXY)s http_srv:app

[program:ldap]
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
command=/app/.venv/bin/python /app/ldap_srv.py